# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmmenu.ui'
#
# Created: Mon May  3 17:02:53 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmmenu(object):
    def setupUi(self, frmmenu):
        frmmenu.setObjectName("frmmenu")
        frmmenu.setEnabled(True)
        frmmenu.resize(1128, 764)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(frmmenu.sizePolicy().hasHeightForWidth())
        frmmenu.setSizePolicy(sizePolicy)
        frmmenu.setMinimumSize(QtCore.QSize(400, 300))
        frmmenu.setMaximumSize(QtCore.QSize(1920, 1200))
        frmmenu.setSizeIncrement(QtCore.QSize(32, 32))
        frmmenu.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(frmmenu)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 1200))
        self.centralwidget.setSizeIncrement(QtCore.QSize(5, 5))
        self.centralwidget.setBaseSize(QtCore.QSize(400, 400))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(-1)
        self.verticalLayout_5.setMargin(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 400))
        self.scrollArea.setMaximumSize(QtCore.QSize(1200, 1200))
        self.scrollArea.setSizeIncrement(QtCore.QSize(10, 10))
        self.scrollArea.setBaseSize(QtCore.QSize(400, 400))
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1103, 713))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(400, 400))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(1200, 1200))
        self.scrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(5, 5))
        self.scrollAreaWidgetContents.setBaseSize(QtCore.QSize(400, 400))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(1, 6, 1061, 676))
        self.widget.setObjectName("widget")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.hboxlayout)
        self.lstarqs = QtGui.QListWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.lstarqs.sizePolicy().hasHeightForWidth())
        self.lstarqs.setSizePolicy(sizePolicy)
        self.lstarqs.setMinimumSize(QtCore.QSize(200, 381))
        self.lstarqs.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstarqs.setObjectName("lstarqs")
        self.verticalLayout_3.addWidget(self.lstarqs)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calcularButton = QtGui.QToolButton(self.widget)
        self.calcularButton.setMinimumSize(QtCore.QSize(151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.calcularButton.setFont(font)
        self.calcularButton.setObjectName("calcularButton")
        self.verticalLayout_2.addWidget(self.calcularButton)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(71, 30))
        self.label_8.setMaximumSize(QtCore.QSize(71, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8)
        self.txtnivel = QtGui.QLineEdit(self.widget)
        self.txtnivel.setMinimumSize(QtCore.QSize(61, 25))
        self.txtnivel.setMaximumSize(QtCore.QSize(61, 25))
        self.txtnivel.setAlignment(QtCore.Qt.AlignCenter)
        self.txtnivel.setObjectName("txtnivel")
        self.horizontalLayout_16.addWidget(self.txtnivel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setMaximumSize(QtCore.QSize(104, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(85, 15))
        self.label_14.setMaximumSize(QtCore.QSize(85, 15))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.txtsigma = QtGui.QLineEdit(self.widget)
        self.txtsigma.setMinimumSize(QtCore.QSize(71, 25))
        self.txtsigma.setMaximumSize(QtCore.QSize(71, 25))
        self.txtsigma.setAlignment(QtCore.Qt.AlignCenter)
        self.txtsigma.setObjectName("txtsigma")
        self.horizontalLayout_15.addWidget(self.txtsigma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lblProjeto_2 = QtGui.QLabel(self.widget)
        self.lblProjeto_2.setMinimumSize(QtCore.QSize(53, 20))
        self.lblProjeto_2.setMaximumSize(QtCore.QSize(53, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblProjeto_2.setFont(font)
        self.lblProjeto_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblProjeto_2.setObjectName("lblProjeto_2")
        self.horizontalLayout_17.addWidget(self.lblProjeto_2)
        self.lblProjeto = QtGui.QLabel(self.widget)
        self.lblProjeto.setMinimumSize(QtCore.QSize(500, 20))
        self.lblProjeto.setMaximumSize(QtCore.QSize(700, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.lblProjeto.setFont(font)
        self.lblProjeto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblProjeto.setObjectName("lblProjeto")
        self.horizontalLayout_17.addWidget(self.lblProjeto)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setMinimumSize(QtCore.QSize(851, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.tabPropert = QtGui.QTabWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabPropert.sizePolicy().hasHeightForWidth())
        self.tabPropert.setSizePolicy(sizePolicy)
        self.tabPropert.setMinimumSize(QtCore.QSize(851, 261))
        self.tabPropert.setMaximumSize(QtCore.QSize(851, 261))
        self.tabPropert.setSizeIncrement(QtCore.QSize(32, 32))
        self.tabPropert.setDocumentMode(False)
        self.tabPropert.setObjectName("tabPropert")
        self.tbParEspec = QtGui.QWidget()
        self.tbParEspec.setObjectName("tbParEspec")
        self.groupBox = QtGui.QGroupBox(self.tbParEspec)
        self.groupBox.setGeometry(QtCore.QRect(200, 71, 641, 161))
        self.groupBox.setMinimumSize(QtCore.QSize(641, 161))
        self.groupBox.setMaximumSize(QtCore.QSize(641, 161))
        self.groupBox.setObjectName("groupBox")
        self.tbElem = QtGui.QTableWidget(self.groupBox)
        self.tbElem.setGeometry(QtCore.QRect(10, 60, 621, 91))
        self.tbElem.setMaximumSize(QtCore.QSize(641, 400))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tbElem.setFont(font)
        self.tbElem.setAutoScrollMargin(16)
        self.tbElem.setRowCount(0)
        self.tbElem.setObjectName("tbElem")
        self.tbElem.setColumnCount(5)
        self.tbElem.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbElem.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbElem.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbElem.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbElem.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tbElem.setHorizontalHeaderItem(4, item)
        self.tbElem.horizontalHeader().setDefaultSectionSize(80)
        self.tbElem.horizontalHeader().setMinimumSectionSize(10)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(160, 0, 280, 20))
        self.label_15.setMinimumSize(QtCore.QSize(280, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 611, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(38, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cbElem = QtGui.QComboBox(self.layoutWidget)
        self.cbElem.setMinimumSize(QtCore.QSize(90, 25))
        self.cbElem.setObjectName("cbElem")
        self.cbElem.addItem("")
        self.horizontalLayout_2.addWidget(self.cbElem)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(41, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.txtConcentra = QtGui.QLineEdit(self.layoutWidget)
        self.txtConcentra.setMinimumSize(QtCore.QSize(101, 25))
        self.txtConcentra.setObjectName("txtConcentra")
        self.horizontalLayout_10.addWidget(self.txtConcentra)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(40, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.txtConcentradesv = QtGui.QLineEdit(self.layoutWidget)
        self.txtConcentradesv.setMinimumSize(QtCore.QSize(71, 25))
        self.txtConcentradesv.setMaximumSize(QtCore.QSize(71, 25))
        self.txtConcentradesv.setObjectName("txtConcentradesv")
        self.horizontalLayout_11.addWidget(self.txtConcentradesv)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cmdIncElem = QtGui.QPushButton(self.layoutWidget)
        self.cmdIncElem.setMinimumSize(QtCore.QSize(80, 25))
        self.cmdIncElem.setObjectName("cmdIncElem")
        self.horizontalLayout_13.addWidget(self.cmdIncElem)
        self.cmdExcElem = QtGui.QPushButton(self.layoutWidget)
        self.cmdExcElem.setMinimumSize(QtCore.QSize(80, 25))
        self.cmdExcElem.setObjectName("cmdExcElem")
        self.horizontalLayout_13.addWidget(self.cmdExcElem)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.groupBox_2 = QtGui.QGroupBox(self.tbParEspec)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 67, 181, 61))
        self.groupBox_2.setMinimumSize(QtCore.QSize(181, 61))
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 26, 152, 23))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rba = QtGui.QRadioButton(self.layoutWidget_3)
        self.rba.setCheckable(True)
        self.rba.setChecked(True)
        self.rba.setObjectName("rba")
        self.horizontalLayout_8.addWidget(self.rba)
        self.rbp = QtGui.QRadioButton(self.layoutWidget_3)
        self.rbp.setCheckable(True)
        self.rbp.setChecked(False)
        self.rbp.setObjectName("rbp")
        self.horizontalLayout_8.addWidget(self.rbp)
        self.layoutWidget_4 = QtGui.QWidget(self.tbParEspec)
        self.layoutWidget_4.setGeometry(QtCore.QRect(12, 6, 768, 28))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.layoutWidget_4)
        self.label.setMinimumSize(QtCore.QSize(121, 16))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEdit.setMinimumSize(QtCore.QSize(641, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.layoutWidget_5 = QtGui.QWidget(self.tbParEspec)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 39, 824, 28))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.data_medida = QtGui.QLabel(self.layoutWidget_5)
        self.data_medida.setMinimumSize(QtCore.QSize(71, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.data_medida.setFont(font)
        self.data_medida.setAlignment(QtCore.Qt.AlignCenter)
        self.data_medida.setObjectName("data_medida")
        self.horizontalLayout_5.addWidget(self.data_medida)
        self.txtdatamedida = QtGui.QDateTimeEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtdatamedida.sizePolicy().hasHeightForWidth())
        self.txtdatamedida.setSizePolicy(sizePolicy)
        self.txtdatamedida.setMinimumSize(QtCore.QSize(135, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtdatamedida.setFont(font)
        self.txtdatamedida.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 2), QtCore.QTime(0, 0, 0)))
        self.txtdatamedida.setObjectName("txtdatamedida")
        self.horizontalLayout_5.addWidget(self.txtdatamedida)
        self.label_10 = QtGui.QLabel(self.layoutWidget_5)
        self.label_10.setMinimumSize(QtCore.QSize(50, 16))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.data_irradiacao = QtGui.QLabel(self.layoutWidget_5)
        self.data_irradiacao.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.data_irradiacao.setFont(font)
        self.data_irradiacao.setAlignment(QtCore.Qt.AlignCenter)
        self.data_irradiacao.setObjectName("data_irradiacao")
        self.horizontalLayout_5.addWidget(self.data_irradiacao)
        self.txtdatah = QtGui.QDateTimeEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtdatah.sizePolicy().hasHeightForWidth())
        self.txtdatah.setSizePolicy(sizePolicy)
        self.txtdatah.setMinimumSize(QtCore.QSize(135, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtdatah.setFont(font)
        self.txtdatah.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 2), QtCore.QTime(0, 0, 0)))
        self.txtdatah.setObjectName("txtdatah")
        self.horizontalLayout_5.addWidget(self.txtdatah)
        self.label_12 = QtGui.QLabel(self.layoutWidget_5)
        self.label_12.setMinimumSize(QtCore.QSize(50, 16))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.layoutWidget_7 = QtGui.QWidget(self.tbParEspec)
        self.layoutWidget_7.setGeometry(QtCore.QRect(15, 156, 175, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lblvivo = QtGui.QLabel(self.layoutWidget_7)
        self.lblvivo.setMinimumSize(QtCore.QSize(100, 20))
        self.lblvivo.setFrameShape(QtGui.QFrame.Panel)
        self.lblvivo.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblvivo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblvivo.setObjectName("lblvivo")
        self.horizontalLayout_7.addWidget(self.lblvivo)
        self.layoutWidget_8 = QtGui.QWidget(self.tbParEspec)
        self.layoutWidget_8.setGeometry(QtCore.QRect(14, 183, 176, 22))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtGui.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lblmorto = QtGui.QLabel(self.layoutWidget_8)
        self.lblmorto.setMinimumSize(QtCore.QSize(100, 20))
        self.lblmorto.setFrameShape(QtGui.QFrame.Panel)
        self.lblmorto.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblmorto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblmorto.setObjectName("lblmorto")
        self.horizontalLayout_9.addWidget(self.lblmorto)
        self.widget1 = QtGui.QWidget(self.tbParEspec)
        self.widget1.setGeometry(QtCore.QRect(16, 122, 167, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.txtmassa = QtGui.QLineEdit(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtmassa.sizePolicy().hasHeightForWidth())
        self.txtmassa.setSizePolicy(sizePolicy)
        self.txtmassa.setMinimumSize(QtCore.QSize(111, 25))
        self.txtmassa.setMaximumSize(QtCore.QSize(111, 25))
        self.txtmassa.setObjectName("txtmassa")
        self.horizontalLayout_6.addWidget(self.txtmassa)
        self.tabPropert.addTab(self.tbParEspec, "")
        self.tbCalib = QtGui.QWidget()
        self.tbCalib.setObjectName("tbCalib")
        self.layoutWidget_9 = QtGui.QWidget(self.tbCalib)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 202, 522, 27))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtGui.QLabel(self.layoutWidget_9)
        self.label_7.setMinimumSize(QtCore.QSize(81, 20))
        self.label_7.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.caliblstwidget = QtGui.QListWidget(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caliblstwidget.sizePolicy().hasHeightForWidth())
        self.caliblstwidget.setSizePolicy(sizePolicy)
        self.caliblstwidget.setMinimumSize(QtCore.QSize(311, 25))
        self.caliblstwidget.setMaximumSize(QtCore.QSize(311, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.caliblstwidget.setFont(font)
        self.caliblstwidget.setAutoScrollMargin(1)
        self.caliblstwidget.setFlow(QtGui.QListView.TopToBottom)
        self.caliblstwidget.setProperty("isWrapping", False)
        self.caliblstwidget.setResizeMode(QtGui.QListView.Adjust)
        self.caliblstwidget.setGridSize(QtCore.QSize(0, 0))
        self.caliblstwidget.setUniformItemSizes(True)
        self.caliblstwidget.setObjectName("caliblstwidget")
        QtGui.QListWidgetItem(self.caliblstwidget)
        QtGui.QListWidgetItem(self.caliblstwidget)
        QtGui.QListWidgetItem(self.caliblstwidget)
        QtGui.QListWidgetItem(self.caliblstwidget)
        self.horizontalLayout_3.addWidget(self.caliblstwidget)
        self.cmdcalibracao = QtGui.QPushButton(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.cmdcalibracao.sizePolicy().hasHeightForWidth())
        self.cmdcalibracao.setSizePolicy(sizePolicy)
        self.cmdcalibracao.setMinimumSize(QtCore.QSize(120, 25))
        self.cmdcalibracao.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cmdcalibracao.setFont(font)
        self.cmdcalibracao.setObjectName("cmdcalibracao")
        self.horizontalLayout_3.addWidget(self.cmdcalibracao)
        self.tabelaCalib = QtGui.QTableWidget(self.tbCalib)
        self.tabelaCalib.setGeometry(QtCore.QRect(3, 20, 591, 133))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabelaCalib.setFont(font)
        self.tabelaCalib.setMidLineWidth(0)
        self.tabelaCalib.setAutoScrollMargin(14)
        self.tabelaCalib.setWordWrap(False)
        self.tabelaCalib.setCornerButtonEnabled(False)
        self.tabelaCalib.setObjectName("tabelaCalib")
        self.tabelaCalib.setColumnCount(7)
        self.tabelaCalib.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaCalib.setHorizontalHeaderItem(6, item)
        self.tabelaCalib.horizontalHeader().setDefaultSectionSize(80)
        self.tabelaCalib.horizontalHeader().setMinimumSectionSize(8)
        self.tabelaCalib.verticalHeader().setDefaultSectionSize(26)
        self.tabelaCalib.verticalHeader().setMinimumSectionSize(13)
        self.groupBox_3 = QtGui.QGroupBox(self.tbCalib)
        self.groupBox_3.setGeometry(QtCore.QRect(650, 20, 191, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget2 = QtGui.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(10, 87, 173, 27))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_16 = QtGui.QLabel(self.widget2)
        self.label_16.setMaximumSize(QtCore.QSize(31, 16))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget2)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(141, 25))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(141, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_21.addWidget(self.lineEdit_5)
        self.widget3 = QtGui.QWidget(self.groupBox_3)
        self.widget3.setGeometry(QtCore.QRect(10, 116, 173, 27))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_17 = QtGui.QLabel(self.widget3)
        self.label_17.setMaximumSize(QtCore.QSize(31, 16))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget3)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(141, 25))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(141, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_22.addWidget(self.lineEdit_6)
        self.widget4 = QtGui.QWidget(self.groupBox_3)
        self.widget4.setGeometry(QtCore.QRect(10, 145, 173, 27))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtGui.QLabel(self.widget4)
        self.label_18.setMaximumSize(QtCore.QSize(31, 16))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.lineEdit_7 = QtGui.QLineEdit(self.widget4)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(141, 25))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(141, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_23.addWidget(self.lineEdit_7)
        self.widget5 = QtGui.QWidget(self.groupBox_3)
        self.widget5.setGeometry(QtCore.QRect(10, 174, 173, 27))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_19 = QtGui.QLabel(self.widget5)
        self.label_19.setMaximumSize(QtCore.QSize(31, 16))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        self.lineEdit_8 = QtGui.QLineEdit(self.widget5)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(141, 25))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(141, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_24.addWidget(self.lineEdit_8)
        self.widget6 = QtGui.QWidget(self.groupBox_3)
        self.widget6.setGeometry(QtCore.QRect(10, 57, 173, 27))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_5 = QtGui.QLabel(self.widget6)
        self.label_5.setMinimumSize(QtCore.QSize(26, 16))
        self.label_5.setMaximumSize(QtCore.QSize(26, 16))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_20.addWidget(self.label_5)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget6)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(141, 25))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(141, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_20.addWidget(self.lineEdit_4)
        self.widget7 = QtGui.QWidget(self.groupBox_3)
        self.widget7.setGeometry(QtCore.QRect(7, 25, 161, 27))
        self.widget7.setObjectName("widget7")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.widget7)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.comboBox = QtGui.QComboBox(self.widget7)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_25.addWidget(self.comboBox)
        self.spinBox = QtGui.QSpinBox(self.widget7)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_25.addWidget(self.spinBox)
        self.label_20 = QtGui.QLabel(self.tbCalib)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 801, 16))
        self.label_20.setMinimumSize(QtCore.QSize(801, 16))
        self.label_20.setMaximumSize(QtCore.QSize(801, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton = QtGui.QPushButton(self.tbCalib)
        self.pushButton.setGeometry(QtCore.QRect(10, 160, 102, 24))
        self.pushButton.setObjectName("pushButton")
        self.tabPropert.addTab(self.tbCalib, "")
        self.tbResCalc = QtGui.QWidget()
        self.tbResCalc.setObjectName("tbResCalc")
        self.cmdImpRes = QtGui.QPushButton(self.tbResCalc)
        self.cmdImpRes.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.cmdImpRes.setObjectName("cmdImpRes")
        self.tableWidget = QtGui.QTableWidget(self.tbResCalc)
        self.tableWidget.setGeometry(QtCore.QRect(8, 30, 831, 191))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.cmdSalvaRes = QtGui.QPushButton(self.tbResCalc)
        self.cmdSalvaRes.setGeometry(QtCore.QRect(90, 0, 75, 23))
        self.cmdSalvaRes.setObjectName("cmdSalvaRes")
        self.tabPropert.addTab(self.tbResCalc, "")
        self.tabResConc = QtGui.QWidget()
        self.tabResConc.setObjectName("tabResConc")
        self.tabWidget_3 = QtGui.QTabWidget(self.tabResConc)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 30, 831, 201))
        self.tabWidget_3.setMaximumSize(QtCore.QSize(831, 295))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gAmostra1 = QtGui.QTableWidget(self.tab_4)
        self.gAmostra1.setGeometry(QtCore.QRect(0, 10, 821, 151))
        self.gAmostra1.setMaximumSize(QtCore.QSize(821, 245))
        self.gAmostra1.setObjectName("gAmostra1")
        self.gAmostra1.setColumnCount(3)
        self.gAmostra1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.gAmostra1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.gAmostra1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.gAmostra1.setHorizontalHeaderItem(2, item)
        self.tabWidget_3.addTab(self.tab_4, "")
        self.cmdImpConcentra = QtGui.QPushButton(self.tabResConc)
        self.cmdImpConcentra.setGeometry(QtCore.QRect(1, 2, 81, 23))
        self.cmdImpConcentra.setObjectName("cmdImpConcentra")
        self.cmdSalvaConcentra = QtGui.QPushButton(self.tabResConc)
        self.cmdSalvaConcentra.setGeometry(QtCore.QRect(101, 2, 81, 23))
        self.cmdSalvaConcentra.setObjectName("cmdSalvaConcentra")
        self.tabPropert.addTab(self.tabResConc, "")
        self.tbEficiencia = QtGui.QWidget()
        self.tbEficiencia.setObjectName("tbEficiencia")
        self.tabPropert.addTab(self.tbEficiencia, "")
        self.verticalLayout_4.addWidget(self.tabPropert)
        self.horizontalLayout_18.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_19.addLayout(self.verticalLayout_5)
        frmmenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmmenu)
        self.statusbar.setObjectName("statusbar")
        frmmenu.setStatusBar(self.statusbar)
        self.actionAbrir = QtGui.QAction(frmmenu)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionFechar = QtGui.QAction(frmmenu)
        self.actionFechar.setObjectName("actionFechar")
        self.actionSair = QtGui.QAction(frmmenu)
        self.actionSair.setObjectName("actionSair")
        self.actionNovo = QtGui.QAction(frmmenu)
        self.actionNovo.setObjectName("actionNovo")
        self.actionAbrir_2 = QtGui.QAction(frmmenu)
        self.actionAbrir_2.setObjectName("actionAbrir_2")
        self.actionSalvar = QtGui.QAction(frmmenu)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSalvar_Como = QtGui.QAction(frmmenu)
        self.actionSalvar_Como.setObjectName("actionSalvar_Como")
        self.actionFechar_2 = QtGui.QAction(frmmenu)
        self.actionFechar_2.setObjectName("actionFechar_2")
        self.actionSobre_o_SAANI = QtGui.QAction(frmmenu)
        self.actionSobre_o_SAANI.setObjectName("actionSobre_o_SAANI")

        self.retranslateUi(frmmenu)
        self.tabWidget.setCurrentIndex(0)
        self.tabPropert.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmmenu)

    def retranslateUi(self, frmmenu):
        frmmenu.setWindowTitle(QtGui.QApplication.translate("frmmenu", "SAANI - Software de Análise por Ativação Neutronica Instrumental", None, QtGui.QApplication.UnicodeUTF8))
        self.calcularButton.setText(QtGui.QApplication.translate("frmmenu", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmmenu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bitstream Vera Sans\';\">Sens. Busca</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.txtnivel.setText(QtGui.QApplication.translate("frmmenu", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("frmmenu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bitstream Vera Sans\';\">Num. SD</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("frmmenu", "( % 1,2 ou 3)", None, QtGui.QApplication.UnicodeUTF8))
        self.txtsigma.setText(QtGui.QApplication.translate("frmmenu", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjeto_2.setText(QtGui.QApplication.translate("frmmenu", "Projeto: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjeto.setText(QtGui.QApplication.translate("frmmenu", "Sem Projeto.SAN", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("frmmenu", "Tab 0", None, QtGui.QApplication.UnicodeUTF8))
        self.tbElem.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("frmmenu", "Elemento", None, QtGui.QApplication.UnicodeUTF8))
        self.tbElem.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("frmmenu", "Energia", None, QtGui.QApplication.UnicodeUTF8))
        self.tbElem.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("frmmenu", "Meia Vida (minutos)", None, QtGui.QApplication.UnicodeUTF8))
        self.tbElem.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("frmmenu", "Concentracao", None, QtGui.QApplication.UnicodeUTF8))
        self.tbElem.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("frmmenu", "Desv.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("frmmenu", "Concentração dos Elementos no Padrão", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmmenu", "Elem.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbElem.setItemText(0, QtGui.QApplication.translate("frmmenu", "As-76", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("frmmenu", "Conc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("frmmenu", "Desv.", None, QtGui.QApplication.UnicodeUTF8))
        self.txtConcentradesv.setText(QtGui.QApplication.translate("frmmenu", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdIncElem.setText(QtGui.QApplication.translate("frmmenu", "Incluir", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdExcElem.setText(QtGui.QApplication.translate("frmmenu", "Excluir", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmmenu", "Tipo de Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.rba.setText(QtGui.QApplication.translate("frmmenu", "Amostra", None, QtGui.QApplication.UnicodeUTF8))
        self.rbp.setText(QtGui.QApplication.translate("frmmenu", "Padrão", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmmenu", "Nome do Arquivo:", None, QtGui.QApplication.UnicodeUTF8))
        self.data_medida.setText(QtGui.QApplication.translate("frmmenu", "Dt Medida:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtdatamedida.setDisplayFormat(QtGui.QApplication.translate("frmmenu", "dd/MM/yyyy HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("frmmenu", "T.Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.data_irradiacao.setText(QtGui.QApplication.translate("frmmenu", "Dt Irradiação", None, QtGui.QApplication.UnicodeUTF8))
        self.txtdatah.setDisplayFormat(QtGui.QApplication.translate("frmmenu", "dd/MM/yyyy HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("frmmenu", "T.Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmmenu", "Tempo Vivo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmmenu", "Tempo Real", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmmenu", "Massa", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPropert.setTabText(self.tabPropert.indexOf(self.tbParEspec), QtGui.QApplication.translate("frmmenu", "Parametros do Espectro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmmenu", "Calibração", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.caliblstwidget.isSortingEnabled()
        self.caliblstwidget.setSortingEnabled(False)
        self.caliblstwidget.item(0).setText(QtGui.QApplication.translate("frmmenu", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.caliblstwidget.item(1).setText(QtGui.QApplication.translate("frmmenu", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.caliblstwidget.item(2).setText(QtGui.QApplication.translate("frmmenu", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.caliblstwidget.item(3).setText(QtGui.QApplication.translate("frmmenu", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.caliblstwidget.setSortingEnabled(__sortingEnabled)
        self.cmdcalibracao.setText(QtGui.QApplication.translate("frmmenu", "Calibrar ...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("frmmenu", "Loc.(can)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("frmmenu", "Ene.(keV)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("frmmenu", "Desv.(can)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("frmmenu", "FWHM (keV)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("frmmenu", "Max. (cont)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("frmmenu", "Area (cont)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaCalib.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("frmmenu", "Desv.(cont)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmmenu", "Calibração em Energia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("frmmenu", "E1=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("frmmenu", "E2=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("frmmenu", "E3=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("frmmenu", "E4=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmmenu", "E0=", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("frmmenu", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("frmmenu", "Quadrática", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("frmmenu", "Polinomial", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("frmmenu", "Picos de Calibração - para editar, clique em um campo; para remover um pico, entre um zero como localização (Loc).", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("frmmenu", "Ajusta Pico", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPropert.setTabText(self.tabPropert.indexOf(self.tbCalib), QtGui.QApplication.translate("frmmenu", "Calibração", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdImpRes.setText(QtGui.QApplication.translate("frmmenu", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("frmmenu", "Energia", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("frmmenu", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("frmmenu", "BG", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("frmmenu", "Resol", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("frmmenu", "Canal Final", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("frmmenu", "Canal Inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("frmmenu", "LP", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("frmmenu", "Cps", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("frmmenu", "S%", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("frmmenu", "Elemento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("frmmenu", "Meia Vida", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("frmmenu", "Massa Padrão", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSalvaRes.setText(QtGui.QApplication.translate("frmmenu", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPropert.setTabText(self.tabPropert.indexOf(self.tbResCalc), QtGui.QApplication.translate("frmmenu", "Resultado dos Cálculos", None, QtGui.QApplication.UnicodeUTF8))
        self.gAmostra1.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("frmmenu", "Elementos", None, QtGui.QApplication.UnicodeUTF8))
        self.gAmostra1.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("frmmenu", "P1", None, QtGui.QApplication.UnicodeUTF8))
        self.gAmostra1.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("frmmenu", "P2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), QtGui.QApplication.translate("frmmenu", "Amostra 1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdImpConcentra.setText(QtGui.QApplication.translate("frmmenu", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSalvaConcentra.setText(QtGui.QApplication.translate("frmmenu", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPropert.setTabText(self.tabPropert.indexOf(self.tabResConc), QtGui.QApplication.translate("frmmenu", "Resultado das Concentrações", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPropert.setTabText(self.tabPropert.indexOf(self.tbEficiencia), QtGui.QApplication.translate("frmmenu", "Eficiência", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setText(QtGui.QApplication.translate("frmmenu", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setStatusTip(QtGui.QApplication.translate("frmmenu", "Abrir Arquivo de Espectro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setShortcut(QtGui.QApplication.translate("frmmenu", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFechar.setText(QtGui.QApplication.translate("frmmenu", "Fechar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFechar.setStatusTip(QtGui.QApplication.translate("frmmenu", "Fechar Arquivo de Espectro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFechar.setShortcut(QtGui.QApplication.translate("frmmenu", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setText(QtGui.QApplication.translate("frmmenu", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setStatusTip(QtGui.QApplication.translate("frmmenu", "Sair do SAANI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setShortcut(QtGui.QApplication.translate("frmmenu", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNovo.setText(QtGui.QApplication.translate("frmmenu", "Novo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNovo.setStatusTip(QtGui.QApplication.translate("frmmenu", "Iniciar Novo Projeto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_2.setText(QtGui.QApplication.translate("frmmenu", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_2.setStatusTip(QtGui.QApplication.translate("frmmenu", "Abrir Projeto Existente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalvar.setText(QtGui.QApplication.translate("frmmenu", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalvar.setStatusTip(QtGui.QApplication.translate("frmmenu", "Salvar Projeto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalvar_Como.setText(QtGui.QApplication.translate("frmmenu", "Salvar Como", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFechar_2.setText(QtGui.QApplication.translate("frmmenu", "Fechar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFechar_2.setStatusTip(QtGui.QApplication.translate("frmmenu", "Fechar Projeto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre_o_SAANI.setText(QtGui.QApplication.translate("frmmenu", "Sobre o SAANI", None, QtGui.QApplication.UnicodeUTF8))

